export type ProjectNavigation = { href: string; title: string };
export type ProjectImage = {
  src: string;
  caption?: string;
  layout?: "full" | "half" | "portrait";
};

export type Project = {
  slug: string;
  number: string;
  title: string;
  question: string;
  location: string;
  year: string;
  status: string;
  typology: string;
  surface?: string;
  team?: string;
  services: string[];
  intro: string;
  strategy: string;
  hero: string;
  cover: string;
  drawing?: string;
  download?: string;
  images: ProjectImage[];
  accent?: string;
  previous: ProjectNavigation;
  next: ProjectNavigation;
};

export const projects: Project[] = [
  {
    slug: "monroe-plaza",
    number: "01",
    title: "Monroe Plaza",
    question: "¿Cómo borrar el límite entre lo público y lo privado?",
    location: "Buenos Aires",
    year: "2026",
    status: "Proyecto académico · Taller VIII",
    typology: "Residencial · Usos mixtos",
    surface: "—",
    team: "Martín Cos · RAStudio",
    services: ["Arquitectura", "Documentación", "Representación"],
    intro: "La propuesta libera los perímetros mediante un núcleo central y transforma la planta baja en una continuidad del espacio urbano. La torre deja de funcionar como objeto aislado para construir una relación más abierta con la ciudad.",
    strategy: "Concentrar la estructura y las circulaciones para liberar el borde, multiplicar las visuales y permitir que el espacio público atraviese el conjunto.",
    hero: "/images/projects/monroe-hero.webp",
    cover: "/images/projects/monroe-01.webp",
    drawing: "/images/projects/monroe-plan.webp",
    download: "/files/monroe-planta-baja.pdf",
    images: [
      { src: "/images/projects/monroe-process.webp", caption: "04 · Sistema y proceso", layout: "full" },
      { src: "/images/projects/monroe-section.webp", caption: "05 · Sección", layout: "half" },
      { src: "/images/projects/monroe-01.webp", caption: "06 · Relación urbana", layout: "half" },
      { src: "/images/projects/monroe-02.webp", caption: "07 · La torre como marco", layout: "full" },
      { src: "/images/projects/monroe-interior.webp", caption: "08 · Espacio doméstico", layout: "portrait" },
      { src: "/images/projects/monroe-detail.webp", caption: "09 · Materia y detalle", layout: "half" },
    ],
    previous: { href: "/proyectos/stand-buick", title: "Stand Buick" },
    next: { href: "/proyectos/escuela-mugica", title: "Escuela Padre Carlos Mugica" },
  },
  {
    slug: "escuela-mugica",
    number: "02",
    title: "Escuela Padre Carlos Mugica",
    question: "¿Puede una escuela convertirse en el corazón de un barrio?",
    location: "Barrio Padre Carlos Mugica, CABA",
    year: "2025",
    status: "1° Premio · Universidad de Palermo",
    typology: "Educación · Equipamiento público",
    team: "Martín Cos · RAStudio",
    services: ["Arquitectura", "Investigación", "Representación"],
    intro: "La escuela se concibe como infraestructura social: un edificio capaz de alojar educación y, al mismo tiempo, ofrecer servicios y espacios de encuentro para el barrio.",
    strategy: "Construir un umbral activo entre lo público y lo privado, haciendo que patios, circulaciones y programas compartidos funcionen como una extensión del tejido comunitario.",
    hero: "/images/projects/escuela-1.webp",
    cover: "/images/projects/escuela-1.webp",
    drawing: "/images/projects/escuela-plan.webp",
    download: "/files/escuela-planta.pdf",
    images: [
      { src: "/images/projects/escuela-2.webp", caption: "04 · Patio como espacio común", layout: "full" },
      { src: "/images/projects/escuela-3.webp", caption: "05 · Umbral urbano", layout: "half" },
      { src: "/images/projects/escuela-4.webp", caption: "06 · Infraestructura social", layout: "half" },
    ],
    accent: "school",
    previous: { href: "/proyectos/monroe-plaza", title: "Monroe Plaza" },
    next: { href: "/proyectos/padl", title: ".PADL" },
  },
  {
    slug: "padl",
    number: "03",
    title: ".PADL",
    question: "¿Cómo convertir un terreno restrictivo en la fortaleza del proyecto?",
    location: "Calle Concepción, CABA",
    year: "2026",
    status: "Proyecto ejecutivo · obra prevista",
    typology: "Deportivo · Comercial",
    surface: "Lote 120 × 17 m",
    team: "RAStudio · PADelCO",
    services: ["Arquitectura", "Proyecto ejecutivo", "Representación"],
    intro: "Un lote de 120 metros de largo por apenas 17 de ancho organiza un complejo de pádel y usos mixtos para PADelCO. La geometría extrema deja de ser un obstáculo y se transforma en la identidad espacial del conjunto.",
    strategy: "Trabajar la profundidad como secuencia: acceso, actividad, pausa y encuentro se encadenan para producir una experiencia continua y legible.",
    hero: "/images/projects/padl-1.webp",
    cover: "/images/projects/padl-1.webp",
    drawing: "/images/projects/padl-plan.webp",
    download: "/files/padl-planta.pdf",
    images: [
      { src: "/images/projects/padl-2.webp", caption: "04 · Profundidad y secuencia", layout: "full" },
      { src: "/images/projects/padl-3.webp", caption: "05 · Actividad", layout: "half" },
      { src: "/images/projects/padl-4.webp", caption: "06 · Encuentro", layout: "half" },
    ],
    accent: "padl",
    previous: { href: "/proyectos/escuela-mugica", title: "Escuela Padre Carlos Mugica" },
    next: { href: "/proyectos/beazley-525", title: "Beazley 525" },
  },
  {
    slug: "beazley-525",
    number: "04",
    title: "Beazley 525",
    question: "¿Cómo mejorar un proyecto sin empezar desde cero?",
    location: "Santos Lugares",
    year: "2026",
    status: "En construcción · Charito SRL",
    typology: "Vivienda multifamiliar",
    team: "RAStudio · Charito SRL",
    services: ["Revisión de proyecto", "Documentación", "Representación"],
    intro: "RAStudio recibió un proyecto aprobado y desarrolló una revisión integral para optimizar su organización, expresión y comunicación sin interrumpir el avance administrativo y constructivo.",
    strategy: "Detectar las decisiones que podían mejorar el conjunto, intervenir con precisión y coordinar esas transformaciones con una obra que ya estaba en marcha.",
    hero: "/images/projects/beazley-living.webp",
    cover: "/images/projects/beazley-living.webp",
    images: [
      { src: "/images/projects/beazley-bedroom.webp", caption: "03 · Dormitorio", layout: "full" },
      { src: "/images/projects/beazley-bathroom.webp", caption: "04 · Materialidad", layout: "half" },
      { src: "/images/projects/beazley-dining.webp", caption: "05 · Vida doméstica", layout: "half" },
    ],
    accent: "beazley",
    previous: { href: "/proyectos/padl", title: ".PADL" },
    next: { href: "/proyectos/casa-das", title: "Casa DAS" },
  },
  {
    slug: "casa-das",
    number: "05",
    title: "Casa DAS",
    question: "¿Cómo hacer que la vida cotidiana se extienda hacia el jardín?",
    location: "Buenos Aires",
    year: "2024",
    status: "Proyecto",
    typology: "Vivienda unifamiliar",
    team: "RAStudio",
    services: ["Arquitectura", "Documentación", "Representación"],
    intro: "Casa DAS organiza la vida doméstica a partir de una relación directa entre los espacios interiores, el jardín y la pileta. La planta baja reúne los ambientes comunes como una secuencia abierta, mientras el nivel superior construye mayor privacidad sin perder el vínculo con el exterior.",
    strategy: "Concentrar circulaciones y servicios para liberar los ambientes principales, encadenar las visuales y convertir cada abertura en una extensión del espacio habitable.",
    hero: "/images/projects/das-hero.webp",
    cover: "/images/projects/das-hero.webp",
    drawing: "/images/projects/das-plan.webp",
    download: "/files/casa-das-plantas.pdf",
    images: [
      { src: "/images/projects/das-structure-01.webp", caption: "04 · Sistema estructural", layout: "half" },
      { src: "/images/projects/das-structure-02.webp", caption: "05 · Lógica constructiva", layout: "half" },
      { src: "/images/projects/das-6.webp", caption: "06 · Cocina como centro doméstico", layout: "full" },
      { src: "/images/projects/das-7.webp", caption: "07 · Continuidad hacia el jardín", layout: "half" },
      { src: "/images/projects/das-5.webp", caption: "08 · Acceso y transición", layout: "half" },
      { src: "/images/projects/das-12.webp", caption: "09 · Habitar junto al exterior", layout: "full" },
      { src: "/images/projects/das-14.webp", caption: "10 · Circulación y luz", layout: "half" },
      { src: "/images/projects/das-15.webp", caption: "11 · Espacio privado", layout: "half" },
      { src: "/images/projects/das-9.webp", caption: "12 · Materialidad", layout: "full" },
    ],
    accent: "das",
    previous: { href: "/proyectos/beazley-525", title: "Beazley 525" },
    next: { href: "/proyectos/museo-del-agua", title: "Museo del Agua" },
  },
  {
    slug: "museo-del-agua",
    number: "06",
    title: "Museo del Agua",
    question: "¿Puede la arquitectura hacernos sentir el mar sin entrar al agua?",
    location: "Mar del Plata",
    year: "2025",
    status: "Proyecto académico · Taller VII",
    typology: "Cultural · Museo de interpretación",
    team: "Martín Cos · RAStudio",
    services: ["Arquitectura", "Investigación", "Documentación", "Representación"],
    intro: "El Museo de Interpretación del Agua propone una experiencia inmersiva antes que una exposición convencional. El edificio toma al mar como materia sensible: luz, reflejos, sonido, movimiento y color construyen un recorrido donde la arquitectura permite aproximarse al agua sin reproducirla literalmente.",
    strategy: "Organizar el programa alrededor de un gran vacío acuático central y convertir la circulación en una secuencia de aproximaciones. Los filtros cromáticos, los cambios de altura y las visuales cruzadas hacen que cada desplazamiento transforme la percepción del espacio.",
    hero: "/images/projects/museo-hero.webp",
    cover: "/images/projects/museo-4.webp",
    drawing: "/images/projects/museo-plan.webp",
    download: "/files/museo-del-agua-planta.pdf",
    images: [
      { src: "/images/projects/museo-axo.webp", caption: "04 · Sistema espacial y constructivo", layout: "full" },
      { src: "/images/projects/museo-section.webp", caption: "05 · Corte longitudinal", layout: "full" },
      { src: "/images/projects/museo-3.webp", caption: "06 · El agua como centro del recorrido", layout: "half" },
      { src: "/images/projects/museo-4.webp", caption: "07 · Vacío, luz y movimiento", layout: "half" },
      { src: "/images/projects/museo-5.webp", caption: "08 · Umbral hacia el mar", layout: "full" },
      { src: "/images/projects/museo-6.webp", caption: "09 · Filtros de color", layout: "half" },
      { src: "/images/projects/museo-8.webp", caption: "10 · Agua, reflejo y permanencia", layout: "half" },
      { src: "/images/projects/museo-7.webp", caption: "11 · Terraza frente al horizonte", layout: "full" },
      { src: "/images/projects/museo-2.webp", caption: "12 · Presencia urbana", layout: "half" },
      { src: "/images/projects/museo-detail.webp", caption: "13 · Detalle constructivo", layout: "portrait" },
    ],
    accent: "museo",
    previous: { href: "/proyectos/casa-das", title: "Casa DAS" },
    next: { href: "/proyectos/sistema-rain", title: "Sistema RAIN" },
  },
  {
    slug: "sistema-rain",
    number: "07",
    title: "Sistema RAIN",
    question: "¿Puede una carpintería convertirse en infraestructura para el agua?",
    location: "Buenos Aires",
    year: "2026",
    status: "Investigación aplicada · Desarrollo técnico",
    typology: "Sistema constructivo · Gestión pluvial",
    team: "Martín Cos · RAStudio",
    services: ["Investigación", "Diseño de sistema", "Documentación técnica", "Modelado 3D"],
    intro: "Sistema RAIN investiga la integración de la captación pluvial dentro de las carpinterías y los encuentros de fachada. En lugar de agregar una instalación visible al edificio, el agua se recibe, conduce y deriva desde piezas que ya forman parte de la envolvente.",
    strategy: "Desarrollar una familia de encuentros adaptables —con antepecho, sobre contrapiso y en curtain wall— y verificar cada transición mediante secciones, axonometrías y modelos de detalle.",
    hero: "/images/projects/rain-6.webp",
    cover: "/images/projects/rain-1.webp",
    drawing: "/images/projects/rain-2.webp",
    images: [
      { src: "/images/projects/rain-5.webp", caption: "04 · Familia de soluciones", layout: "full" },
      { src: "/images/projects/rain-6.webp", caption: "05 · Recorrido integrado del agua", layout: "full" },
      { src: "/images/projects/rain-1.webp", caption: "06 · Encuentro y derivación", layout: "portrait" },
      { src: "/images/projects/rain-3.webp", caption: "07 · Carpintería sobre contrapiso", layout: "half" },
      { src: "/images/projects/rain-4.webp", caption: "08 · Integración en curtain wall", layout: "half" },
    ],
    accent: "rain",
    previous: { href: "/proyectos/museo-del-agua", title: "Museo del Agua" },
    next: { href: "/proyectos/ndp150", title: "NDP150" },
  },
  {
    slug: "ndp150",
    number: "08",
    title: "NDP150",
    question: "¿Cómo anticipar una vivienda para comunicarla antes de terminar la obra?",
    location: "Nortes del Pilar · Pilar",
    year: "2026",
    status: "En construcción · Visualización comercial",
    typology: "Vivienda unifamiliar · Visualización",
    team: "RAStudio",
    services: ["Interpretación de documentación", "Diseño interior", "Materialidad", "Visualización 3D"],
    intro: "El cliente llegó con un plano municipal aprobado y una obra por comenzar. RAStudio transformó esa documentación técnica en una imagen completa de la vivienda, capaz de comunicar su atmósfera, materialidad y manera de habitar durante el proceso de construcción.",
    strategy: "Leer el plano aprobado, resolver espacialmente aquello que todavía no estaba definido y construir una narrativa visual coherente para acompañar la comercialización de la propiedad.",
    hero: "/images/projects/ndp-4.webp",
    cover: "/images/projects/ndp-1.webp",
    drawing: "/images/projects/ndp-plan.webp",
    download: "/files/ndp150-planta.pdf",
    images: [
      { src: "/images/projects/ndp-1.webp", caption: "04 · Estar, comedor y jardín", layout: "full" },
      { src: "/images/projects/ndp-2.webp", caption: "05 · Cocina y comedor", layout: "half" },
      { src: "/images/projects/ndp-3.webp", caption: "06 · Baño", layout: "half" },
      { src: "/images/projects/ndp-5.webp", caption: "07 · Dormitorio", layout: "full" },
    ],
    accent: "ndp",
    previous: { href: "/proyectos/sistema-rain", title: "Sistema RAIN" },
    next: { href: "/proyectos/stand-buick", title: "Stand Buick" },
  },
  {
    slug: "stand-buick",
    number: "09",
    title: "Stand Buick",
    question: "¿Cómo convertir un esquema preliminar en una experiencia espacial verificable?",
    location: "México",
    year: "2026",
    status: "Propuesta · Visualización de evento",
    typology: "Stand exterior · Experiencia de marca",
    team: "RAStudio · Cliente privado",
    services: ["Interpretación de concepto", "Diseño espacial", "Verificación dimensional", "Visualización 3D"],
    intro: "El punto de partida fueron esquemas realizados por el cliente en PowerPoint: ideas de uso, medidas, mobiliario y referencias de marca. El trabajo consistió en traducir esa información a un espacio tridimensional creíble antes de avanzar con su ejecución.",
    strategy: "Ordenar las circulaciones, verificar escalas y relaciones entre exhibición, hospitalidad y permanencia, y consolidar una estética común sin perder las intenciones originales del cliente.",
    hero: "/images/projects/buick-1.webp",
    cover: "/images/projects/buick-4.webp",
    drawing: "/images/projects/buick-sketch-1.webp",
    images: [
      { src: "/images/projects/buick-sketch-2.webp", caption: "04 · Esquema inicial del cliente", layout: "full" },
      { src: "/images/projects/buick-2.webp", caption: "05 · Traducción espacial", layout: "full" },
      { src: "/images/projects/buick-3.webp", caption: "06 · Hospitalidad y exhibición", layout: "half" },
      { src: "/images/projects/buick-4.webp", caption: "07 · Presencia de marca", layout: "half" },
      { src: "/images/projects/buick-5.webp", caption: "08 · Escala, circulación y permanencia", layout: "full" },
    ],
    accent: "buick",
    previous: { href: "/proyectos/ndp150", title: "NDP150" },
    next: { href: "/proyectos/monroe-plaza", title: "Monroe Plaza" },
  },
];

export const projectBySlug = Object.fromEntries(projects.map((project) => [project.slug, project])) as Record<string, Project>;
