import Image from "next/image";
import Link from "next/link";
const projects=[
 {n:"01",title:"Monroe Plaza",type:"Residencial · Buenos Aires",href:"/proyectos/monroe-plaza",img:"/images/projects/monroe-hero.webp",q:"Disolver el límite entre lo público y lo privado."},
 {n:"02",title:"Escuela Padre Carlos Mugica",type:"Arquitectura pública · CABA",href:"/proyectos/escuela-mugica",img:"/images/projects/escuela-1.webp",q:"Arquitectura como infraestructura social."},
 {n:"03",title:".PADL",type:"Deportivo · Comercial",href:"/proyectos/padl",img:"/images/projects/padl-1.webp",q:"Transformar la restricción en identidad."},
 {n:"04",title:"Beazley 525",type:"Vivienda · En construcción",href:"/proyectos/beazley-525",img:"/images/projects/beazley-living.webp",q:"Intervenir con precisión sobre lo existente."}
];
export default function Home(){return <main className="v4Home">
 <section className="v4Hero"><Image src="/images/projects/monroe-hero.webp" alt="Arquitectura de RAStudio" fill priority sizes="100vw" className="cover"/><div className="v4Shade"/><div className="v4HeroTop"><span>RAStudio</span><span>Buenos Aires · Argentina</span></div><div className="v4HeroCopy"><h1>Architecture is the art<br/>of making ideas <em>inhabitable.</em></h1><div><p>Arquitectura · Representación · Construcción</p><a href="#work">Recorrer ↓</a></div></div></section>
 <section className="v4Statement"><p className="eyebrow">Práctica de arquitectura</p><h2>Diseñamos proyectos donde la idea, el documento y la obra forman parte de una misma conversación.</h2><div><p>RAStudio es una práctica dirigida por Martín Cos. Trabajamos desde la observación inicial hasta la comunicación final, integrando arquitectura, documentación, representación y construcción.</p><Link href="/practice">Conocer la práctica ↗</Link></div></section>
 <section id="work" className="v4Work"><div className="v4SectionHead"><p className="eyebrow">01 · Work</p><h2>Proyectos seleccionados</h2></div>{projects.map(p=><Link className="v4Project" href={p.href} key={p.title}><div className="v4ProjectMedia"><Image src={p.img} alt={p.title} fill sizes="100vw" className="cover"/></div><div className="v4ProjectMeta"><span>{p.n}</span><div><p>{p.type}</p><h3>{p.title}</h3><small>{p.q}</small></div><b>↗</b></div></Link>)}</section>
 <section className="v4Process"><div className="v4SectionHead"><p className="eyebrow">02 · Process</p><h2>Una secuencia continua de decisiones.</h2></div><div>{["Observar","Preguntar","Diseñar","Documentar","Construir","Comunicar"].map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div><Link href="/practice">Ver el proceso completo ↗</Link></section>
 <section className="v4Martin"><div className="v4MartinImage"><Image src="/images/martin/desk.webp" alt="Martín Cos trabajando" fill sizes="50vw" className="cover"/></div><div><p className="eyebrow">03 · Martín Cos</p><h2>Una práctica personal, técnica y en constante evolución.</h2><p>Más de siete años desarrollando proyectos entre el diseño, la documentación, la obra y nuevas herramientas de representación.</p><Link href="/martin-cos">Conocer la trayectoria ↗</Link></div></section>
 <section className="v4Closing"><p className="eyebrow">04 · Contacto</p><h2>Toda arquitectura comienza con una conversación.</h2><Link href="/contacto">Comenzar un proyecto <span>↗</span></Link></section>
 </main>}
